services:
  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/ocremix-data
    init: true
    volumes:
      - ./:/home/python/ocremix-data
    working_dir: /home/python/ocremix-data
