services:
  build-pages:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/ocremix-data/ocremixdata.py
      - build-pages
    image: ghcr.io/williamjacksn/ocremix-data
    init: true
    volumes:
      - ./:/home/python/ocremix-data
    working_dir: /home/python/ocremix-data

  gen-openapi-spec:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/ocremix-data/gen-openapi-spec.py
    image: ghcr.io/williamjacksn/ocremix-data
    init: true
    volumes:
      - ./:/home/python/ocremix-data
    working_dir: /home/python/ocremix-data

  import-missing:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/ocremix-data/ocremixdata.py
      - import-missing
    image: ghcr.io/williamjacksn/ocremix-data
    init: true
    volumes:
      - ./:/home/python/ocremix-data
    working_dir: /home/python/ocremix-data

  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.13
    init: true
    volumes:
      - ./:/home/python/ocremix-data
    working_dir: /home/python/ocremix-data

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/ocremix-data
    init: true
    volumes:
      - ./:/home/python/ocremix-data
    working_dir: /home/python/ocremix-data

  update:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/ocremix-data/ocremixdata.py
      - update
    image: ghcr.io/williamjacksn/ocremix-data
    init: true
    volumes:
      - ./:/home/python/ocremix-data
    working_dir: /home/python/ocremix-data
