[project]
name = "ocremix-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "htpy>=25.10.0",
    "lxml>=6.0.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.12",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
